### ISSUE TITLE
illegal parameter () passed to task at argument 1

### ISSUE THREAD

**Issue by JunoBoom** [krakjoe/parallel#221] opened 2021-09-27 15:04 UTC
```
$myClass = MyClass();
\parallel\run(function($myClass){
    $myClass->run();
}, [$myClass]);
```

This always returns error illegal parameter () passed to task at argument 1

If I do this : 

```
$myClass = MyClass();
\parallel\run(function($myClass){
    return $myClass;
}, [$myClass->run]);
```

It doesn't throw an error anymore . 

Why it's not possible to add the class without a function and call it inside paralllel function ?

**Comment by akbaryahya** [comment] 2021-10-20 00:26
I gave up looking for this solution all functions outside don't work if inside \parallel\run, even like this

`
$myClass  = new tes(array( 'abc'=>'hi', 'xda'=>'xx'));
\parallel\run(function ($myClass) {return $myClass->fu();}, [$myClass]);
`
If you try getting an error:
PHP Fatal error:  Uncaught Error: Call to undefined method parallel\Runtime\Type\Unavailable::fu()

**Comment by cmb69** [comment] 2022-03-14 16:24
Please provide a [short, self contained and correct example](http://sscce.org/) that demonstrates the bug.

**Comment by mercurykd** [comment] 2022-07-11 14:58
@cmb69 
dockerfile:
```
from php:7.4.29-zts
run apt update && apt install -y libpthread-stubs0-dev
run pecl install parallel
run docker-php-ext-enable parallel
workdir /app
```
index.php:
```
<?php

class Test
{
    public $a = 42;

    public function dd()
    {
        var_dump($this->a);
    }
}

$t = new Test();
\parallel\run(function ($o) {
    $o->dd();
}, [$t]);
```

Fatal error: Uncaught Error: Call to undefined method parallel\Runtime\Type\Unavailable::dd() in /app/index.php:15                                                                                             
Stack trace:                                                                                                                                                                                                   
#0 {main}                                                                                                                                                                                                      
  thrown in /app/index.php on line 15

**Comment by cmb69** [comment] 2022-07-11 16:04
Ah, thank you @mercurykd! This is not a bug, though. The problem is that the parallel runtime doesn't know class `Test`, and as such assigns the `parallel\Runtime\Type\Unavailable` class. You need to make the class definition available to the parallel runtime, e.g. by using `parallel\bootstrap`. So move the class definition to its own file `Test.php`, and then change the given test script to:
````php
<?php

require __DIR__ . "/Test.php";

\parallel\bootstrap(__DIR__ . "/Test.php");
$t = new Test();
\parallel\run(function ($o) {
    var_dump($o);
}, [$t]);
````
Running this yields the expected:
````
object(Test)#2 (1) {
  ["a"]=>
  int(42)
}
````
The docs are not particularly clear on this, so could probably be improved.

**Comment by krakjoe** [comment] 2022-10-27 21:45
There is mention of this in the doc: https://www.php.net/manual/en/class.parallel-runtime.php

Not sure if there wasn't at the time, but that looks like enough to me.

Anyone is free to improve the docs, of course ... but closing this.

**Closed as not planned by krakjoe** 2022-10-27 21:45 UTC
Labels: docs
