### ISSUE TITLE
How can I use parallel on Windows?

### ISSUE THREAD

**Issue by nicollassilva** [krakjoe/parallel#280] opened 2023-08-17 11:12 UTC
Sorry if this is the thousandth time you've answered this, but actually reading all the issues I still have doubts about how to correctly install the extension for Windows.

I'm using **PHP 8.1.22 ZTS** and **Windows 10**, how do I install this on my machine?

Thanks for your response.

**Comment by Jeangowhy** [comment] 2023-09-26 05:37
How to build paralle on Windows? How to solve pthread dependence?

**Comment by jasonccs** [comment] 2023-10-15 04:40
How can I use parallel on Windows? #280

**Comment by krakjoe** [comment] 2024-05-18 18:13
Sorry but this is not a bug, so closing this.

**Closed as completed by krakjoe** 2024-05-18 18:13 UTC

**Comment by cmb69** [comment] 2024-07-21 16:38
Just for the record: Windows DLLs are available via https://pecl.php.net/package/parallel. How to install the extension is explained on https://www.php.net/manual/en/parallel.setup.php.
