### ISSUE TITLE
[parallel\Events\Event\Error] construction of Events\Event objects is not allowed

### ISSUE THREAD

**Issue by enumag** [krakjoe/parallel#125] opened 2020-02-11 09:01 UTC
I'm trying to use this along with [Amp](https://github.com/amphp/amp) and [ext-event](https://pecl.php.net/package/event). The EventLoop is throwing this error:

```
[parallel\Events\Event\Error]
construction of Events\Event objects is not allowed
```

The stack trace points to creation of the `\Event` object [here](https://github.com/amphp/amp/blob/2ac3b550c4997f2ec304faa63c8b2885079a2dc4/lib/Loop/EventDriver.php#L244) which doesn't make sense since it's creating an instance of `\Event`, not `\parallel\Events\Event`.

I'm guessing these two extensions are somehow incompatible with each other?

**Comment by krakjoe** [comment] 2020-02-12 09:57
It looks like something is inheriting from parallel, that message can only be thrown by the Event::__construct in the parallel\Events namespace ... something must be inheriting it, somehow.

This extension doesn't perform any of the kind of magic that would cause it to force classes in another namespace to inherit from it's own hierarchy so I would investigate the other extension and ask amp maintainers to have a look ...

I'm going to close this because I don't think it's a bug here, however, it still exists for reference in other repos and if you feel like adding some example (very simple) reproducing code I'll take a look at it myself when I have time.

**Closed as completed by krakjoe** 2020-02-12 09:57 UTC
