### ISSUE TITLE
Running on localhost

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#186] opened 2021-04-24 09:41 UTC
Tried everything (as described [here](https://stackoverflow.com/questions/57800012/) ) but still it ends with "ERR_CONNECTION_RESET".

Any solutions to make it work on wamp-server? 

(btw, I saw similar [issue here](https://github.com/krakjoe/parallel/issues/173), but it does not have any insights and was closed)

**Comment by harryqt** [comment] 2021-04-30 04:33
Just a small reminder that Parallel extension only works in PHP CLI.

**Comment by krakjoe** [comment] 2024-05-18 17:50
This is a configuration issue, not a bug, so closing this.

**Closed as completed by krakjoe** 2024-05-18 17:50 UTC
