### ISSUE TITLE
Install fail on "make test"

### ISSUE THREAD

**Issue by dividerbeam** [krakjoe/parallel#231] opened 2022-03-16 18:04 UTC
root@converter:~/parallel# make test

Build complete.
Don't forget to run 'make test'.

=====================================================================
PHP         : /root/bin/php-latest/bin/php
PHP_SAPI    :
Deprecated: Return type of parallel\Events::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
cli
PHP_VERSION : 8.1.3
ZEND_VERSION: 4.1.3
PHP_OS      : Linux - Linux converter 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64
INI actual  : /root/parallel/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /root/bin/php-latest/bin/php-cgi
PHP_SAPI    : cgi-fcgi
PHP_VERSION : 8.1.3
ZEND_VERSION: 4.1.3
PHP_OS      : Linux - Linux converter 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64
INI actual  : /root/parallel/tmp-php.ini
More .INIs  :
Deprecated: Return type of parallel\Events::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0

---------------------------------------------------------------------
---------------------------------------------------------------------
PHP         : /root/bin/php-latest/bin/phpdbg
PHP_SAPI    : phpdbg
PHP_VERSION : 8.1.3
ZEND_VERSION: 4.1.3
PHP_OS      : Linux - Linux converter 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64
INI actual  : /root/parallel/tmp-php.ini
More .INIs  :
Deprecated: Return type of parallel\Events::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0

---------------------------------------------------------------------
CWD         : /root/parallel
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2022-03-16 18:05:08
=====================================================================
FAIL Check basic parallel operation [tests/base/001.phpt]
FAIL Check parallel global scope [tests/base/002.phpt]
FAIL Check parallel return values [tests/base/003.phpt]
FAIL Check parallel closed [tests/base/004.phpt]
FAIL Check parallel ini [tests/base/005.phpt]
FAIL ZEND_DECLARE_CLASS [tests/base/008.phpt]
FAIL ZEND_DECLARE_ANON_CLASS [tests/base/009.phpt]
FAIL ZEND_DECLARE_INHERITED_CLASS [tests/base/010.phpt]
FAIL ZEND_BIND_STATIC (OK) [tests/base/011.phpt]
FAIL ZEND_BIND_STATIC (FAIL) [tests/base/012.phpt]
FAIL ZEND_DECLARE_LAMBDA_FUNCTION [tests/base/013.phpt]
FAIL ZEND_DECLARE_FUNCTION [tests/base/014.phpt]
FAIL ZEND_YIELD [tests/base/015.phpt]
FAIL ZEND_YIELD_FROM [tests/base/016.phpt]
FAIL Copy arguments (OK) [tests/base/017.phpt]
FAIL Copy arginfo (FAIL) [tests/base/018.phpt]
FAIL Copy argv (FAIL) [tests/base/019.phpt]
FAIL Copy arginfo (OK) [tests/base/020.phpt]
FAIL Copy try [tests/base/021.phpt]
FAIL return destroyed [tests/base/022.phpt]
FAIL bailed [tests/base/023.phpt]
FAIL parallel can create parallel [tests/base/024.phpt]
FAIL parallel may return arrays [tests/base/025.phpt]
FAIL parallel may accept arrays [tests/base/026.phpt]
FAIL Future may not be constructed [tests/base/027.phpt]
FAIL parallel bootstrap [tests/base/028.phpt]
FAIL parallel bootstrap fail [tests/base/029.phpt]
FAIL parallel future exception [tests/base/030.phpt]
FAIL parallel future saved [tests/base/031.phpt]
FAIL parallel future saved null [tests/base/032.phpt]
FAIL parallel bootstrap exception [tests/base/033.phpt]
FAIL parallel bootstrap compile error [tests/base/034.phpt]
FAIL parallel killed [tests/base/035.phpt]
FAIL parallel return values [tests/base/036.phpt]
FAIL parallel Future exception with trace [tests/base/037.phpt]
FAIL parallel Future value refcounted unfetched [tests/base/038.phpt]
FAIL parallel Future done [tests/base/039.phpt]
FAIL parallel streams [tests/base/041.phpt]
FAIL parallel auto globals [tests/base/042.phpt]
FAIL parallel Closure::fromCallable internal [tests/base/043.phpt]
FAIL parallel copy persistent repeat [tests/base/044.phpt]
XLEAK parallel cancellation (not running) [tests/base/045.phpt]   XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
XLEAK parallel cancellation (running) [tests/base/046.phpt]   XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
FAIL parallel cancellation (ready) [tests/base/047.phpt]
XLEAK parallel cancellation (already cancelled) [tests/base/048.phpt]   XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
XLEAK parallel cancellation (runtime killed) [tests/base/049.phpt]   XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
XLEAK parallel cancellation (value on cancelled) [tests/base/050.phpt]   XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
FAIL parallel l2 cache copies [tests/base/051.phpt]
FAIL parallel check arginfo cached [tests/base/052.phpt]
FAIL parallel check scope changed in task [tests/base/053.phpt]
FAIL parallel check cache hit literal string [tests/base/054.phpt]
FAIL parallel task check cached, Future used second time [tests/base/055.phpt]
FAIL parallel object check finds illegal property in table [tests/base/056.phpt]
FAIL parallel object check finds illegal property inline [tests/base/057.phpt]
FAIL parallel object check finds non-existent class [tests/base/058.phpt]
FAIL parallel class check cached [tests/base/059.phpt]
FAIL parallel class check invalid member [tests/base/060.phpt]
FAIL parallel runtime copy [tests/base/061.phpt]
FAIL parallel immutable class load [tests/base/062.phpt]
FAIL parallel cache unset flags on literals [tests/base/063.phpt]
FAIL parallel check type list simple [tests/base/064.phpt]
FAIL parallel check type list missing definition [tests/base/065.phpt]
FAIL parallel check type list property [tests/base/066.phpt]
FAIL parallel check type list property not found [tests/base/067.phpt]
FAIL Check basic channel operation (argument) [tests/channel/001.phpt]
FAIL Check make/open/cast [tests/channel/002.phpt]
FAIL Check channel operation (unbuffered) [tests/channel/003.phpt]
FAIL Check channel operation (buffered) [tests/channel/004.phpt]
FAIL Check basic channel operation duplicate name [tests/channel/005.phpt]
FAIL Check basic channel operation non-existent name [tests/channel/006.phpt]
FAIL Check channel operation send on closed [tests/channel/007.phpt]
FAIL Check channel operation recv on closed [tests/channel/008.phpt]
FAIL Check channel operation close on closed [tests/channel/009.phpt]
FAIL Check channel make arguments [tests/channel/010.phpt]
FAIL Check channel send arguments [tests/channel/011.phpt]
FAIL Check Channel comparison [tests/channel/014.phpt]
FAIL Check Channel debug [tests/channel/015.phpt]
FAIL Check Channel share [tests/channel/016.phpt]
FAIL Check Channel closures inside arrays [tests/channel/017.phpt]
FAIL Check Channel closures inside object properties [tests/channel/018.phpt]
FAIL Check Channel closures inside object properties (declared) [tests/channel/019.phpt]
FAIL Check buffered Channel drains [tests/channel/020.phpt]
FAIL Check anonymous Channel [tests/channel/021.phpt]
FAIL Check clone Channel [tests/channel/022.phpt]
FAIL Check serialize Channel [tests/channel/023.phpt]
FAIL Check closures in arginfo/argv (OK) [tests/closures/001.phpt]
FAIL Check closures in return [tests/closures/002.phpt]
FAIL Check closures over channel buffered [tests/closures/003.phpt]
FAIL Check closures over channel unbuffered [tests/closures/004.phpt]
FAIL Check closures over channel unbuffered destroy last [tests/closures/005.phpt]
FAIL Check closures no nested declarations [tests/closures/006.phpt]
FAIL Check closures statics [tests/closures/007.phpt]
FAIL Check closures statics scopes [tests/closures/008.phpt]
FAIL Check closures static changes [tests/closures/009.phpt]
FAIL Check closures binding [tests/closures/010.phpt]
FAIL Check closures binding static [tests/closures/011.phpt]
FAIL Check closures cached function check [tests/closures/012.phpt]
FAIL Check Events setInput overwrite [tests/events/001.phpt]
FAIL Check events add duplicate [tests/events/003.phpt]
FAIL Check events remove non-existent [tests/events/004.phpt]
FAIL Check events remove [tests/events/005.phpt]
FAIL Check events input [tests/events/007.phpt]
FAIL Check Event constructor disallowed [tests/events/009.phpt]
FAIL Check Events poll no arguments [tests/events/011.phpt]
FAIL Check Events Future error [tests/events/012.phpt]
FAIL Check Events Future killed [tests/events/013.phpt]
FAIL Check Events Input invalid value [tests/events/014.phpt]
FAIL Check Events timeout/non-blocking mode [tests/events/015.phpt]
FAIL Check Events Future cancelled [tests/events/016.phpt]
FAIL Check Events Channel closed [tests/events/017.phpt]
FAIL Check events loop channel [tests/events/wait/001.phpt]
FAIL Check events loop future [tests/events/wait/002.phpt]
FAIL Check events timeout [tests/events/wait/003.phpt]
FAIL Check events wait nothing [tests/events/wait/004.phpt]
FAIL Check Events non-blocking [tests/events/wait/005.phpt]
FAIL Check Events non-blocking iterator exception [tests/events/wait/006.phpt]
FAIL Check functional parallel operation [tests/functional/001.phpt]
FAIL Check functional bootstrap [tests/functional/002.phpt]
FAIL Check functional future [tests/functional/003.phpt]
FAIL Check functional reuse [tests/functional/004.phpt]
FAIL Check functional bootstrap error (previously set) [tests/functional/005.phpt]
FAIL Check functional bootstrap error (set after run) [tests/functional/006.phpt]
FAIL Check functional bootstrap error (set in task) [tests/functional/007.phpt]
FAIL Check handlers write property [tests/handlers/001.phpt]
FAIL Check handlers read property [tests/handlers/002.phpt]
FAIL Check handlers write dimension [tests/handlers/003.phpt]
FAIL Check handlers read dimension [tests/handlers/004.phpt]
FAIL Check handlers ptr ptr [tests/handlers/005.phpt]
FAIL Check sync __construct [tests/sync/001.phpt]
FAIL Check sync get/set [tests/sync/002.phpt]
=====================================================================
TIME END 2022-03-16 18:05:11

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   41
---------------------------------------------------------------------

Number of tests :  130               130
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :  125 ( 96.2%) ( 96.2%)
Tests passed    :    0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :    3 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Check basic parallel operation [tests/base/001.phpt]
Check parallel global scope [tests/base/002.phpt]
Check parallel return values [tests/base/003.phpt]
Check parallel closed [tests/base/004.phpt]
Check parallel ini [tests/base/005.phpt]
ZEND_DECLARE_CLASS [tests/base/008.phpt]
ZEND_DECLARE_ANON_CLASS [tests/base/009.phpt]
ZEND_DECLARE_INHERITED_CLASS [tests/base/010.phpt]
ZEND_BIND_STATIC (OK) [tests/base/011.phpt]
ZEND_BIND_STATIC (FAIL) [tests/base/012.phpt]
ZEND_DECLARE_LAMBDA_FUNCTION [tests/base/013.phpt]
ZEND_DECLARE_FUNCTION [tests/base/014.phpt]
ZEND_YIELD [tests/base/015.phpt]
ZEND_YIELD_FROM [tests/base/016.phpt]
Copy arguments (OK) [tests/base/017.phpt]
Copy arginfo (FAIL) [tests/base/018.phpt]
Copy argv (FAIL) [tests/base/019.phpt]
Copy arginfo (OK) [tests/base/020.phpt]
Copy try [tests/base/021.phpt]
return destroyed [tests/base/022.phpt]
bailed [tests/base/023.phpt]
parallel can create parallel [tests/base/024.phpt]
parallel may return arrays [tests/base/025.phpt]
parallel may accept arrays [tests/base/026.phpt]
Future may not be constructed [tests/base/027.phpt]
parallel bootstrap [tests/base/028.phpt]
parallel bootstrap fail [tests/base/029.phpt]
parallel future exception [tests/base/030.phpt]
parallel future saved [tests/base/031.phpt]
parallel future saved null [tests/base/032.phpt]
parallel bootstrap exception [tests/base/033.phpt]
parallel bootstrap compile error [tests/base/034.phpt]
parallel killed [tests/base/035.phpt]
parallel return values [tests/base/036.phpt]
parallel Future exception with trace [tests/base/037.phpt]
parallel Future value refcounted unfetched [tests/base/038.phpt]
parallel Future done [tests/base/039.phpt]
parallel streams [tests/base/041.phpt]
parallel auto globals [tests/base/042.phpt]
parallel Closure::fromCallable internal [tests/base/043.phpt]
parallel copy persistent repeat [tests/base/044.phpt]
parallel cancellation (ready) [tests/base/047.phpt]
parallel l2 cache copies [tests/base/051.phpt]
parallel check arginfo cached [tests/base/052.phpt]
parallel check scope changed in task [tests/base/053.phpt]
parallel check cache hit literal string [tests/base/054.phpt]
parallel task check cached, Future used second time [tests/base/055.phpt]
parallel object check finds illegal property in table [tests/base/056.phpt]
parallel object check finds illegal property inline [tests/base/057.phpt]
parallel object check finds non-existent class [tests/base/058.phpt]
parallel class check cached [tests/base/059.phpt]
parallel class check invalid member [tests/base/060.phpt]
parallel runtime copy [tests/base/061.phpt]
parallel immutable class load [tests/base/062.phpt]
parallel cache unset flags on literals [tests/base/063.phpt]
parallel check type list simple [tests/base/064.phpt]
parallel check type list missing definition [tests/base/065.phpt]
parallel check type list property [tests/base/066.phpt]
parallel check type list property not found [tests/base/067.phpt]
Check basic channel operation (argument) [tests/channel/001.phpt]
Check make/open/cast [tests/channel/002.phpt]
Check channel operation (unbuffered) [tests/channel/003.phpt]
Check channel operation (buffered) [tests/channel/004.phpt]
Check basic channel operation duplicate name [tests/channel/005.phpt]
Check basic channel operation non-existent name [tests/channel/006.phpt]
Check channel operation send on closed [tests/channel/007.phpt]
Check channel operation recv on closed [tests/channel/008.phpt]
Check channel operation close on closed [tests/channel/009.phpt]
Check channel make arguments [tests/channel/010.phpt]
Check channel send arguments [tests/channel/011.phpt]
Check Channel comparison [tests/channel/014.phpt]
Check Channel debug [tests/channel/015.phpt]
Check Channel share [tests/channel/016.phpt]
Check Channel closures inside arrays [tests/channel/017.phpt]
Check Channel closures inside object properties [tests/channel/018.phpt]
Check Channel closures inside object properties (declared) [tests/channel/019.phpt]
Check buffered Channel drains [tests/channel/020.phpt]
Check anonymous Channel [tests/channel/021.phpt]
Check clone Channel [tests/channel/022.phpt]
Check serialize Channel [tests/channel/023.phpt]
Check closures in arginfo/argv (OK) [tests/closures/001.phpt]
Check closures in return [tests/closures/002.phpt]
Check closures over channel buffered [tests/closures/003.phpt]
Check closures over channel unbuffered [tests/closures/004.phpt]
Check closures over channel unbuffered destroy last [tests/closures/005.phpt]
Check closures no nested declarations [tests/closures/006.phpt]
Check closures statics [tests/closures/007.phpt]
Check closures statics scopes [tests/closures/008.phpt]
Check closures static changes [tests/closures/009.phpt]
Check closures binding [tests/closures/010.phpt]
Check closures binding static [tests/closures/011.phpt]
Check closures cached function check [tests/closures/012.phpt]
Check Events setInput overwrite [tests/events/001.phpt]
Check events add duplicate [tests/events/003.phpt]
Check events remove non-existent [tests/events/004.phpt]
Check events remove [tests/events/005.phpt]
Check events input [tests/events/007.phpt]
Check Event constructor disallowed [tests/events/009.phpt]
Check Events poll no arguments [tests/events/011.phpt]
Check Events Future error [tests/events/012.phpt]
Check Events Future killed [tests/events/013.phpt]
Check Events Input invalid value [tests/events/014.phpt]
Check Events timeout/non-blocking mode [tests/events/015.phpt]
Check Events Future cancelled [tests/events/016.phpt]
Check Events Channel closed [tests/events/017.phpt]
Check events loop channel [tests/events/wait/001.phpt]
Check events loop future [tests/events/wait/002.phpt]
Check events timeout [tests/events/wait/003.phpt]
Check events wait nothing [tests/events/wait/004.phpt]
Check Events non-blocking [tests/events/wait/005.phpt]
Check Events non-blocking iterator exception [tests/events/wait/006.phpt]
Check functional parallel operation [tests/functional/001.phpt]
Check functional bootstrap [tests/functional/002.phpt]
Check functional future [tests/functional/003.phpt]
Check functional reuse [tests/functional/004.phpt]
Check functional bootstrap error (previously set) [tests/functional/005.phpt]
Check functional bootstrap error (set after run) [tests/functional/006.phpt]
Check functional bootstrap error (set in task) [tests/functional/007.phpt]
Check handlers write property [tests/handlers/001.phpt]
Check handlers read property [tests/handlers/002.phpt]
Check handlers write dimension [tests/handlers/003.phpt]
Check handlers read dimension [tests/handlers/004.phpt]
Check handlers ptr ptr [tests/handlers/005.phpt]
Check sync __construct [tests/sync/001.phpt]
Check sync get/set [tests/sync/002.phpt]
=====================================================================

=====================================================================
EXPECTED LEAK TEST SUMMARY
---------------------------------------------------------------------
parallel cancellation (not running) [tests/base/045.phpt]  XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
parallel cancellation (running) [tests/base/046.phpt]  XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
parallel cancellation (already cancelled) [tests/base/048.phpt]  XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
parallel cancellation (runtime killed) [tests/base/049.phpt]  XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
parallel cancellation (value on cancelled) [tests/base/050.phpt]  XLEAK REASON: The interrupt we use for cancellation is not treated in a thread safe way in core
=====================================================================

You may have found a problem in PHP.
This report can be automatically sent to the PHP QA team at
http://qa.php.net/reports and http://news.php.net/php.qa.reports
This gives us a better understanding of PHP's behavior.
If you don't want to send the report immediately you can choose
option "s" to save it.  You can then email it to qa-reports@lists.php.net later.
Do you want to send this report now? [Yns]: n
make: *** [Makefile:132: test] Error 1

**Comment by cmb69** [comment] 2022-03-16 18:21
This appears to be a duplicate of #217.

**Closed as completed by cmb69** 2022-03-16 18:21 UTC
Labels: duplicate

**Comment by dividerbeam** [comment] 2022-03-16 18:45
> This appears to be a duplicate of #217.

i change event.c and run make test again:

root@converter:~/parallel# make test
/bin/bash /root/parallel/libtool --mode=compile cc -I. -I/root/parallel -I/root/parallel/include -I/root/parallel/main -I/root/parallel -I/root/bin/php-latest/include/php -I/root/bin/php-latest/include/php/main -I/root/bin/php-latest/include/php/TSRM -I/root/bin/php-latest/include/php/Zend -I/root/bin/php-latest/include/php/ext -I/root/bin/php-latest/include/php/ext/date/lib -I/root/parallel  -DHAVE_CONFIG_H  -g -O2   -Wall -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1  -DZEND_COMPILE_DL_EXT=1 -c /root/parallel/src/events.c -o src/events.lo  -MMD -MF src/events.dep -MT src/events.lo
 cc -I. -I/root/parallel -I/root/parallel/include -I/root/parallel/main -I/root/parallel -I/root/bin/php-latest/include/php -I/root/bin/php-latest/include/php/main -I/root/bin/php-latest/include/php/TSRM -I/root/bin/php-latest/include/php/Zend -I/root/bin/php-latest/include/php/ext -I/root/bin/php-latest/include/php/ext/date/lib -I/root/parallel -DHAVE_CONFIG_H -g -O2 -Wall -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /root/parallel/src/events.c -MMD -MF src/events.dep -MT src/events.lo  -fPIC -DPIC -o src/.libs/events.o
In file included from /root/bin/php-latest/include/php/main/php.h:35,
                 from /root/parallel/src/parallel.h:21,
                 from /root/parallel/src/events.c:21:
/root/parallel/src/events.c:249:33: error: 'php_parallel_events_poll_arginfo' undeclared here (not in a function); did you mean 'php_parallel_events_count_arginfo'?
  249 |     PHP_ME(Events, poll,        php_parallel_events_poll_arginfo, ZEND_ACC_PUBLIC)
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/bin/php-latest/include/php/Zend/zend_API.h:77:80: note: in definition of macro 'ZEND_RAW_FENTRY'
   77 | #define ZEND_RAW_FENTRY(zend_name, name, arg_info, flags)   { zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
      |                                                                                ^~~~~~~~
/root/bin/php-latest/include/php/main/php.h:375:25: note: in expansion of macro 'ZEND_ME'
  375 | #define PHP_ME          ZEND_ME
      |                         ^~~~~~~
/root/parallel/src/events.c:249:5: note: in expansion of macro 'PHP_ME'
  249 |     PHP_ME(Events, poll,        php_parallel_events_poll_arginfo, ZEND_ACC_PUBLIC)
      |     ^~~~~~
make: *** [Makefile:243: src/events.lo] Error 1

![image](https://user-images.githubusercontent.com/52495131/158667829-561e2e49-6837-441f-93f2-f5b84dc09255.png)
